# BungeeJSON configuration file.
# There is not a lot to configure.

# Port where the HTTP server will run.
http-server-port: 7432

# Authentication provider.
# Available: api-key, ip-based, dummy
# See http://minecraft.imaginarycode.com/bungeejson:auth for information.
auth-type: api-key